### PR TITLE
Hello

### PR DESCRIPTION
**Pull request by Tuzar-learner**
Please add.

### CODE REVIEW

**Comment by abrahamparayil** [comment]
Please change `null` to `none`. Also consider add an avatar. :)

**Comment by Tuzar-learner** [comment]
> Please change `null` to `none`. Also consider add an avatar. :)

Done

**Comment by abrahamparayil** [comment]
Thanks for attending! 🥳

**Comment by Tuzar-learner** [comment]
> Thanks for attending! 🥳

Thank you for providing the wonderful section.

**Pull request merged**
